default:
  image: python:3.13.0-bookworm


stages:
  - testing

ruff:
  stage: testing
  script:
    - pip install -r app/ci-requirements.txt
    - ruff check --verbose
  tags:
    - home

black:
  stage: testing
  script:
    - pip install -r app/ci-requirements.txt
    - black --diff app/get_wallpaper.py
  tags:
    - home

mypy:
  stage: testing
  script:
    - pip install -r app/ci-requirements.txt
    - mypy app/get_wallpaper.py
  tags:
    - home

bandit:
  stage: testing
  script:
    - pip install -r app/ci-requirements.txt
    - bandit -c bandit.yaml -r app/
  tags:
    - home