default:
  image: python:3.13.0-bookworm


stages:
  - testing

ruff:
  stage: testing
  script:
    - pip install -r app/ci-requirements.txt
  tags:
    - home

black:
  stage: testing
  script:
    - pip install -r app/ci-requirements.txt
  tags:
    - home

mypy:
  stage: testing
  script:
    - pip install -r app/ci-requirements.txt
  tags:
    - home

bandit:
  stage: testing
  script:
    - pip install -r app/ci-requirements.txt
  tags:
    - home