ruff:
  stage: testing
  script:
    - echo "Running ruff"
  tags:
    - home

black:
  stage: testing
  script:
    - echo "Running black"
  tags:
    - home

mypy:
  stage: testing
  script:
    - echo "mypy"
  tags:
    - home

bandit:
  stage: testing
  script:
    - echo "Running bandit"
  tags:
    - home