[lint]
unfixable = ["F401", "F841", "PIE804", "T201"]
select = ["B", "D", "E", "F", "I", "T20", "W", "N", "YTT", "ASYNC", "S", "A", "C4", "DTZ", "T10", "PIE", "PT", "RSE", "SLF", "SIM", "TCH", "PTH", "PGH", "PLC", "RUF", "RET"]
pydocstyle = {convention = "google"}
# Allow lines to be as long as 120.
line-length = 120